### ISSUE TITLE
Widgets must be within a MapView, but that's not a requirement in the JS AP

### ISSUE THREAD

**Issue by morehavoc** [dymaptic/dy-blazor-api-core#17]
In the JS Api, I can put a widget on the map, or I can place it in an arbitrary location within the DOM tree and simply specify the MapView that it should be attached to. For example, I might want to put the basemap switcher under a menu on the left of the map with other menu items for my app (not be limited to placing it only on top of the map view).

In the JS Api, you can specify the DOM node like: 

```javascript
const basemaps = new BasemapGallery({
        view,
        container: "basemaps-container"
      });
```

Today, our API only allows you to position these within the `MapView` (and that's how the reference to the view is created, the widget is a child of the view). This is very powerful, but it would be nice to be able to place these outside the map as well, by providing the link to the view we want it to use.

**Comment by TimPurdum** [comment]
merged with #32
