### ISSUE TITLE
Javascript File uses a Global `view` variable

### ISSUE THREAD

**Issue by morehavoc** [dymaptic/dy-blazor-api-core#3]
Currently, the `arcGisJsInterop.js` file uses a global view variable to keep track of the map view. 

https://github.com/dymaptic/dy-blazor-api-core/blob/98de2d7d0fa6c6e00317a0f636c4497156497718/src/dymaptic.Blazor.GIS.API.Core/wwwroot/arcGisJsInterop.js#L4

I believe that this makes it so that we can't have multiple map views, it is also kind of just asking for trouble I think (having a global variable for this). Can we make this so the reference is just passed back and forth for each function that needs it? Basically can we make all of these functions truly functional and not have any global mutation?

**Comment by morehavoc** [comment]
It is still _effectively_ global though, it's more like a static instance. 

I like this Guid idea. Could we centralize this even more and have an `dyObjects` dictionary and a couple of methods to get/set/delete them? I'm thinking since we are using Guids we could store all the objects in the same dictionary, and then in any JS interop code, we can get the object out of that central repository. That way we don't have to have different dictionaries for every type of object we need to store.

**Comment by TimPurdum** [comment]
> It is still effectively global though, it's more like a static instance.
Yes, that's true, it's static, can't have multiple instances.
Does `dyObjects` make more sense than separate `views`, `graphics`, etc.? I feel like named collections would be more clear, and I can only imagine a small handful of them.

**Comment by morehavoc** [comment]
I was leaning towards `dyObjects` as a generic solution for this problem. So that we don't have to create another list, etc. when some new item comes along. We can build a set of utility functions on the JS and C# (or maybe classes) side to handle all this and then we just call that/extend the correct base class and we magically have a connection between the C# object and the JS object.

If we do it as separate lists, we'll have to write code for each one, so I guess I'm asking if we can do this in a generic way that would be useful in the future, both for this API, but also just building blazor apps?

**Comment by TimPurdum** [comment]
> 

There is a lot of Blazor development that requires little to no JavaScript at all, and even more where object references would not need to be kept. This API is somewhat unique in that regards. Still, I will tinker around with a unified dictionary and see what I come up with for this.
